### ISSUE TITLE
Error when instantiating CMRWebApi Object

### ISSUE THREAD

**Issue by sdeshbhratar** [davidyack/Xrm.Tools.CRMWebAPI#72]
Hello

I am getting an error during the call to instantiate the CRMWebAPI object:Exception:
CRMWebAPI api = new CRMWebAPI(resource + "/api/data/v9.0/", result.AccessToken);

   at Xrm.Tools.WebAPI.CRMWebAPI..ctor(String apiUrl, String accessToken, Guid callerID, Func`2 getAccessToken)
   at WcfService1.Service1.<GetDataStringAsync>d__7.MoveNext()
   
Inner Exception
   Could not load file or assembly 'System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
      
Stack trace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at WcfService1.Service1.GetDataString(String value) in 
   at SyncInvokeGetDataString(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)

The token generated is a valid token based on client credentials flow and I am able to use the token in Postman to retrieve data from Dynamics. Please let me know if you need additional details.

**Comment by davidyack** [comment]
You have a reference problem "Could not load file or assembly 'System.Net.Http, Version=4.1.1.0, Culture=neutral, "  What version of .net (full framework or core) are you using?
